language: node_js
sudo: false
branches:
  only:
    - master
node_js:
  - "12"
  - "node"
env:
  - CI=true
  - TRAVIS=true
  - LANG=en_US.UTF-8
  - CONTINUOUS_INTEGRATION=true
install:
  # Required by Electron
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm ci
before_script:
  # Building sources
  - npm run build
script:
  - npm run test
