language: node_js
node_js:
  - "12"
  - "node"
sudo: false
os:
- linux
dist: bionic
apt:
  sources:
  - google-chrome
branches:
  only:
    - master
env: 
  - CXX=g++-4.8 
install:
  - npm i
script:
  - npm run test
