language: node_js
sudo: false
branches:
  only:
    - master
node_js:
  - "12"
  - "node"
env:
  - CI=true
  - TRAVIS=true
  - LANG=en_US.UTF-8
  - CONTINUOUS_INTEGRATION=true
install:
  - npm i
before_script:
  # Building sources
  - npm run build
script:
  - npm run test
