language: node_js
node_js:
  - "12"
  - "node"
sudo: false
os:
- linux
dist: bionic
apt:
  sources:
  - google-chrome
branches:
  only:
    - master
env: 
  - Cclang and llvm 7
  - cmake 3.12.4
  - gcc 7.4.0
  - ccache 3.4.1
  - shellcheck 0.6.0
  - shfmt 2.6.3
install:
  - npm i
script:
  - npm run test
