language: node_js
node_js:
  - "12"
  - "node"
os:
- linux
dist: bionic
apt:
  sources:
  - google-chrome
branches:
  only:
    - master
before_install:
  npm i -S -D twilio
install:
  - npm i
script:
  - npm run test
